# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: earth
  theme_night: earth
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Mapper'
    description: 'Site personnel de Jérémy Garniaux, géographe, cartographe & développeur.'
    twitter: 'mapperfr'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    # notice: '© {year} Jérémy Garniaux - [cc by nc sa 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).'
    notice: '© {year} Jérémy Garniaux - [cc by nc sa 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).<br><div id="wcb" class="carbonbadge"></div>
<script src="https://unpkg.com/website-carbon-badges@1.1.3/b.min.js" defer></script>'

    license:
      enable: false
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '2 Jan 2006'
  time_format: '3:04 PM'
  address_format: fr-fr

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - python
  math:
    enable: false
  diagram:
    enable: false
  privacy_pack:
    enable: false
  repository:
    # url: 'https://github.com/mapperfr/mapperfr-source'
    url: 'https://code.mapper.fr/jeremy/mapperfr-source'
    content_dir: content
    branch: master
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true

security:
  allow_frame: true
